version: '3.7'
services:
    webserver:
      image: tensorlakehouse-openeo-driver:latest
      container_name: webserver
      networks:
        - neta
      command: bash tensorlakehouse_openeo_driver/run_gunicorn.sh
      environment:
        - PYTHONPATH=/opt/app-root/src/tensorlakehouse-openeo-driver
        - BROKER_URL=${BROKER_URL}
        - RESULT_BACKEND=${RESULT_BACKEND}
        - CREDENTIALS=${CREDENTIALS}
        - GEODN_DISCOVERY_PASSWORD=${GEODN_DISCOVERY_PASSWORD}
        - GEODN_DISCOVERY_USERNAME=${GEODN_DISCOVERY_USERNAME}
        - DASK_SCHEDULER_ADDRESS=${DASK_SCHEDULER_ADDRESS}
        - STAC_URL=http://stac:8080/
        - APPID_ISSUER=${APPID_ISSUER}
        - APPID_USERNAME=${APPID_USERNAME}
        - APPID_PASSWORD=${APPID_PASSWORD}
        - OPENEO_AUTH_CLIENT_ID=${OPENEO_AUTH_CLIENT_ID}
        - OPENEO_AUTH_CLIENT_SECRET=${OPENEO_AUTH_CLIENT_SECRET}
      ports:
        - "9092:9091"
      restart: always
      depends_on:
        - stac
        - worker
    worker:
      image: tensorlakehouse-openeo-driver:latest
      container_name: worker
      command: celery -A tensorlakehouse_openeo_driver.tasks worker -s /tmp/celerybeat-schedule --concurrency 2 --prefetch-multiplier 1 -Ofair -B  -Q tensorlakehouse-queue --loglevel=info
      environment:
        - PYTHONPATH=/opt/app-root/src/tensorlakehouse-openeo-driver
        - BROKER_URL=${BROKER_URL}
        - RESULT_BACKEND=${RESULT_BACKEND}
        - CREDENTIALS=${CREDENTIALS}
        - GEODN_DISCOVERY_PASSWORD=${GEODN_DISCOVERY_PASSWORD}
        - GEODN_DISCOVERY_USERNAME=${GEODN_DISCOVERY_USERNAME}
        - DASK_SCHEDULER_ADDRESS=${DASK_SCHEDULER_ADDRESS}
        - STAC_URL=http://stac:8080/
        - APPID_ISSUER=${APPID_ISSUER}
        - APPID_USERNAME=${APPID_USERNAME}
        - APPID_PASSWORD=${APPID_PASSWORD}
        - OPENEO_AUTH_CLIENT_ID=${OPENEO_AUTH_CLIENT_ID}
        - OPENEO_AUTH_CLIENT_SECRET=${OPENEO_AUTH_CLIENT_SECRET}
      restart: always
    stac:
      image: localhost/stac-fastapi-pgstac:latest
      container_name: stac
      networks:
        - neta
      ports:
        - "8080:8080"
      environment:
        - APP_HOST=0.0.0.0
        - APP_PORT=8080
        - ENVIRONMENT=local
        - WEBCONCURRENCY=2
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - POSTGRES_DBNAME=${POSTGRES_DBNAME}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_HOST_READER=${POSTGRES_HOST_READER}
        - POSTGRES_HOST_WRITER=${POSTGRES_HOST_WRITER}
        - POSTGRES_PORT=${POSTGRES_PORT}
      restart: always
networks:
  neta:
    driver: bridge



