apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8787
    name: dashboard
  - port: 8786
    name: scheduler
  selector:
    app: dask-scheduler