{{ if .Values.applyingess }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tensorlakehouse-ingress
spec:
  rules:
  - host: stac.tensorlakehouse
    http:
      paths:
      - path: /stac-explorer
        pathType: Prefix
        backend:
          service:
            name:  stac-explorer
            port:
              number: 8080
      - path: /pgstac
        pathType: Prefix
        backend:
          service:
            name: pgstac-fastapi
            port:
              number: 8080 
{{ end }}