---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openeo-geodn-driver
  name: openeo-geodn-driver
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 9091
    targetPort: 9091
    protocol: TCP
  selector:
    app: openeo-geodn-driver