kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tensorlakehouse-openeo-driver
  namespace: {{ .Values.namespace }}
  labels:
    app: tensorlakehouse-openeo-driver
    ingress-router: {{ .Values.routes.ingressRouter }}
  annotations:
    openshift.io/host.generated: 'true'
    haproxy.router.openshift.io/timeout: 2700s
spec:
  host: {{ .Values.routes.openeo }}
  to:
    kind: Service
    name: tensorlakehouse-openeo-driver
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
status:
  ingress:
    - host: {{ .Values.routes.openeo }}
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
      routerCanonicalHostname: {{ .Values.routes.router }}