---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgstac-fastapi
  name: pgstac-fastapi
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: pgstac-fastapi