---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgstac
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgstac
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgstac
    spec:
      containers:
        - name: pypgstac
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PGHOST
              value: pgstac
            - name: PGUSER
              value: username
            - name: PGPASSWORD
              value: password
            - name: PGDATABASE
              value: postgis
          image: quay.io/tensorlakehouse/stac-fastapi-pypgstac:latest
          imagePullPolicy: Always
        - name: pgstac
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: username
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: postgis
            - name: PGUSER
              value: username
            - name: PGPASSWORD
              value: password
            - name: PGDATABASE
              value: postgis
          image: quay.io/tensorlakehouse/stac-fastapi-pgstac:latest
          imagePullPolicy: Always
      restartPolicy: Always