---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgstacpostgis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgstacpostgis
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgstacpostgis
    spec:
      {{ if .Values.use_pull_secret }}
      imagePullSecrets:
      - name: {{ .Values.pull_secret }}
      {{ end }}
      containers:
        - name: pgstacpostgis
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: username
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: postgis
            - name: PGUSER
              value: username
            - name: PGPASSWORD
              value: password
            - name: PGDATABASE
              value: postgis
          image: docker.io/tensorlakehouse/stac-fastapi-pgstac:0.1.4
          imagePullPolicy: Always
      restartPolicy: Always