---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: stac-explorer
  namespace: {{ .Values.namespace }}
  generation: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stac-explorer
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stac-explorer
    spec:
      {{ if .Values.use_pull_secret }}
      imagePullSecrets:
      - name: {{ .Values.pull_secret }}
      {{ end }}
      containers:
        - name: stac-explorer
          ports:
            - containerPort: 8080
              protocol: TCP
          image: docker.io/tensorlakehouse/stac-browser:latest
          imagePullPolicy: Always
          command: ["/start.sh"]
      restartPolicy: Always