---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stac-fastapi-sqlalchemy
  name: stac-fastapi-sqlalchemy
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: stac-fastapi-sqlalchemy